### PR TITLE
Expose Gesture Area Height to settings 

### PR DESCRIPTION
**Pull request by penk**

### CODE REVIEW

**Comment by RS102839** [comment]
Please add the DCO line to your pull request:  
http://www.openwebosproject.org/community/governance/dco/#.UG8bdVZx7Wg

**Comment by kkweng** [comment]
To the commit! To the commit !

**Comment by RS102839** [comment]
Also add a check to HostQtDesktop::init in HostQtDesktop.cpp, just before m_info.displayBuffer = 0;
If GESTURE_AREA_HEIGHT less than (windowHeight/30) or greater than (windowHeight/10) , force Settings::LunaSettings()->gestureAreaHeight to be (windowHeight/16).

Since the value is now coming from the "....conf" file, we need to trap for silly values.

**Comment by penk** [comment]
committed, would "GestureAreaHeight=0" be the right way to completely hide the gesture area (for devices with physical Home button)?

**Comment by RS102839** [comment]
Interesting question.  Experiment by setting the GESTURE_AREA_HEIGHT to zero.  My suspicion is you would need to add an extra test to avoid trying to create the button.

This also means the code would need to be changed to allow a valid value of zero, because currently a zero entry is indistinguishable from no entry, and therefore you would get a default of 50.

**Comment by penk** [comment]
It seems working with current patch: http://i.imgur.com/J4Zsu.jpg

Should I add test in HostQtDesktop::setCentralWidget?

**Comment by RS102839** [comment]
I wasn't able to take these as a pull request and had to cherry-pick them instead.
I'm therefore closing this pull request as completed, since the changes have been applied.

**Pull request closed without merging**
