### PR TITLE
Doxygen docs

### PR DESCRIPTION
**Pull request by ghost**
Ongoing process of adding Doxygen documentation.

### CODE REVIEW

**Comment by ghost** [comment]
Just a quick FYI on this: most of these changes are being cherry-picked (with some modification, where differences arise) from https://github.com/tyrok1/LunaSysMgr

**Comment by RS102839** [comment]
We're looking forward to contributions, and to make that easy and well-understood, we're following in the footsteps of the popular Certificate of Origin used by Linux.   You can see the details here:
http://www.openwebosproject.org/governance/dco

**Comment by ghost** [comment]
Couple questions:
1. Where do I put the certificate statement?
2. Does it have to be a real name instead of a username?  If so, I may need to close this and have someone else submit a pull request and certification on behalf of myself as I'd prefer to stick with my username.

**Comment by RS102839** [comment]
The DCO requirement is quite common in Open Source and our policy is based on that used for Linux kernel contributions.
Having someone else submit doesn't seem a good approach.  
You probably should contact me directly by email to work this out :-)

**Comment by ghost** [comment]
Would love to.  What's your e-mail?  :)

**Comment by RS102839** [comment]
My email is in the DCO of my recent submissions.  :-)

However, the internal consensus is to move this discussion to the (new) openwebos-dev forum so others may participate and that the discussion may persist:
          http://mailman.openwebosproject.org/mailman/listinfo/openwebos-dev

**Comment by ghost** [comment]
Closing due to not wanting to use my real name.

**Pull request closed without merging**
