### PR TITLE
Application manager service

### PR DESCRIPTION
**Pull request by ericblade**
Open-webOS-DCO-1.0-Signed-off-by:Eric Blade blade.eric@gmail.com

### CODE REVIEW

**Comment by ericblade** [comment]
I applied this to LunaCE on my TouchPad several weeks ago, and have put it in LunaCE for wider testing, now. I am satisfied that fixing this error does not cause any further errors, at least in any situation that I've managed to run into in every day use.

**Comment by RS102839** [comment]
Sorry, we can't accept changes to the copyright block.

**Comment by ericblade** [comment]
OK, there has been some debate over the correct way to add one's name, as is apparently required by Apache License 2.0, section 4-2. "You must cause any modified files to carry prominent notices stating that You changed the files".  

If this is not something that we need to worry about, then I can simply remove it -- or is there some other place that it should be noted?

**Comment by ericblade** [comment]
according to Keith's message on the mailing list, this should be ready to go now

**Pull request closed without merging**
