### PR TITLE
Support for 64-bit Linux

### PR DESCRIPTION
**Pull request by panda-z**
I'm trying to build desktop luna-sysmgr on 64-bit Linux.

And these changes are tested on ArchLinux(x86_64) and it works very well.

### CODE REVIEW

**Comment by RS102839** [comment]
Thanks for the input. We will look into this. :-)

**Comment by panda-z** [comment]
It seems I've made some mistakes while operating git, I'm new to git. Perhaps I should create a new branch and submit this changes to a new pull request?

**Comment by RS102839** [comment]
Well, it certainly does no harm to close out and redo.  :-)

When we looked at it, the "tweak to desktop.pri" seemed like it might have some side-effects, so perhaps you should try to avoid relying on that.

**Comment by panda-z** [comment]
Hi, @RS102839 , I checked the code and found the "MACHINE_NAME" in desktop.pri only affects the output directory. It is referenced by "DESTDIR" in sysmgr.pro and UnitTests/InputTouch/InputTouch.pro. But I also found in tests/QWebPage/desktop.pri, the "DESTDIR" is manually set to "./debug-x86". Is this the side-effects you mean? Or something else? Please point out the problem if you can. Thank you.

**Comment by RS102839** [comment]
I see some scripts, not all of which are yet public, which view ...-x86 as running in "Desktop" mode.  For the moment, It would seem better to leave that even when building 64 bit.

**Comment by panda-z** [comment]
OK, I see. I'll close this pull request and wait for more components to be public released.

**Comment by RS102839** [comment]
We would prefer the change to Desktop.pri came through seperately, but the other changes are of immediate interest.

**Pull request closed without merging**
