### PR TITLE
Doxygen docs for Main.cpp

### PR DESCRIPTION
**Pull request by KyleMaas**
Open-webOS-DCO-1.0-Signed-off-by: Kyle Maas kylemaasdev@gmail.com

### CODE REVIEW

**Comment by RS102839** [comment]
Please rebase

**Comment by RS102839** [comment]
I tried to cherry-pick the change and couldn't, so please rebase the change and we will see if that works.

**Comment by KyleMaas** [comment]
Well, that came through awfully messy.  Do you need a new branch and pull request for this, or are you able to work with this?

**Comment by ericblade-owo** [comment]
I merged pull request #24 based on RS102839's prior approval.

**Comment by KyleMaas** [comment]
Closing, since this is merged in.

**Pull request closed without merging**
